### ISSUE TITLE
Go SDK does not compile

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws-apigateway#51]
### What happened?

The Go SDK cannot be used - it fails to compile with:

```
# github.com/pulumi/pulumi-aws-apigateway/sdk/go/apigateway
../../../../go/pkg/mod/github.com/pulumi/pulumi-aws-apigateway/sdk@v0.0.7/go/apigateway/restAPI.go:92:11: undefined: RouteArgs
```

### Steps to reproduce

Run any program which tries to reference v0.0.7 or later of this package in Go, such as the Go example in the examples folder.

### Expected Behavior

It compiels.

### Actual Behavior

It doesn't compile.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
This was broken by the changes in https://github.com/pulumi/pulumi-aws-apigateway/commit/0dad4f9342a1e4f823bfbafcee9d254a9d039b46#diff-2a40442b8af6a6d09227e933b4ef86132782123c989e0909c2223785c6c27619 as part of https://github.com/pulumi/pulumi-aws-apigateway/pull/20.

**Comment by stack72** [comment]
@AaronFriel as discussed

**Comment by AaronFriel** [comment]
I've bisected the change to a commit in this PR: https://github.com/pulumi/pulumi/pull/7943
